#FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
FROM registry.access.redhat.com/ubi8/dotnet-31 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY aspnetapp/*.csproj ./aspnetapp/
RUN dotnet restore

# copy everything else and build app
COPY aspnetapp/. ./aspnetapp/
WORKDIR /app/aspnetapp
RUN dotnet publish -c Release -o out


#FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
FROM registry.access.redhat.com/ubi8/dotnet-30-runtime AS runtime
WORKDIR /app
COPY --from=build /app/aspnetapp/out ./
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
